name: 01-action-pipeline
on:
  push:
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "hello world...!"
      - name: second step
        run: |
          echo "this is second step"
          echo "multi line statement"
