name: 01-action-pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "hello world...!"
      - name: second step
        run: |
          echo "this is second step"
          echo "multi line statement"
  my-failed-job:
    runs-on: ubuntu-latest
    steps:
      - name: failed-job
        run: |
          echo "failed job"
          exit 1

  my-second-job:
    runs-on: windows-latest
    steps:
      - name: second job steps - step 1
        shell: bash
        run: |
          echo "this is windows runner"
