name: expression-workflow
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
env:
  MY_NAME: muraly

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        if: ${{inputs.debug}}
        run: |
          echo "value of debug is : ${{inputs.debug}}"
  echo-2:
    runs-on: windows-latest
    steps:
      - name: second-job
        shell: bash
        if: inputs.debug==false
        run: |
          echo "this is $MY_NAME"
          echo "value of debug is new: ${{inputs.debug}}"
