name: expression-yml
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: true

jobs:
  start-up:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] - the debug run'
        if: ${{inputs.debug}}
        run: |
          echo "this is debug run ${{inputs.debug}}"
